import { AnalysisState } from '../types';

export interface ErrorReport {
  errorType: 'validation' | 'vision_api' | 'parsing' | 'no_analysis' | 'unknown';
  errorMessage: string;
  userFriendlyMessage: string;
  recommendations: string[];
  metadata?: {
    platform: string;
    uiType: string;
    audience: string;
  };
}

export function generateErrorReport(
  state: AnalysisState,
  errorMessage?: string,
): ErrorReport {
  const metadata = state.metadata || {
    platform: 'Unknown',
    uiType: 'Unknown',
    audience: 'Unknown',
  };

  // Determine error type from summary weaknesses or error message
  const weaknesses = state.summary?.weaknesses || [];
  const hasAnalysisIssue = weaknesses.some((w) =>
    w.toLowerCase().includes('unable to analyse'),
  );
  const hasValidationIssue = errorMessage?.includes('Image validation failed') || false;
  const hasParsingIssue = weaknesses.some((w) =>
    w.toLowerCase().includes('invalid model output') ||
    w.toLowerCase().includes('parsed') ||
    w.toLowerCase().includes('json'),
  );

  let errorType: ErrorReport['errorType'] = 'unknown';
  let userFriendlyMessage = '';
  let recommendations: string[] = [];

  if (hasValidationIssue) {
    errorType = 'validation';
    userFriendlyMessage =
      'The image could not be validated. It may be too small, have an extreme aspect ratio, or be corrupted.';
    recommendations = [
      'Ensure the image is at least 100x100 pixels',
      'Check that the aspect ratio is not greater than 20:1',
      'Verify the image file is not corrupted',
      'Try using a PNG or JPEG format',
      'Ensure the image contains actual UI content (not blank or placeholder)',
    ];
  } else if (hasParsingIssue) {
    errorType = 'parsing';
    userFriendlyMessage =
      'The Vision API response could not be parsed. This may be due to an unexpected response format or corrupted data.';
    recommendations = [
      'Retry the analysis - this may be a temporary issue',
      'Try a different image to verify the issue',
      'Check your OpenAI API key and quota',
      'Ensure you have a stable internet connection',
      'If the issue persists, try updating AgentUX',
    ];
  } else if (hasAnalysisIssue) {
    errorType = 'no_analysis';
    userFriendlyMessage =
      'The Vision API was unable to analyze the image. This may be due to image size, aspect ratio, or lack of visual content.';
    recommendations = [
      'Try using a larger image (at least 200x200 pixels recommended)',
      'Ensure the image has a reasonable aspect ratio (not extremely wide or tall)',
      'Verify the image contains clear UI elements',
      'Check that the image is not too dark or low contrast',
      'Try cropping to focus on specific UI components',
    ];
  } else {
    errorType = 'unknown';
    userFriendlyMessage =
      'An unexpected error occurred during analysis. Please review the error details and try again.';
    recommendations = [
      'Retry the analysis',
      'Check your OpenAI API key configuration',
      'Verify the image file is valid',
      'Try a different image',
      'Check AgentUX logs for more details',
    ];
  }

  return {
    errorType,
    errorMessage: errorMessage || weaknesses.join('; ') || 'Unknown error',
    userFriendlyMessage,
    recommendations,
    metadata: {
      platform: metadata.platform,
      uiType: metadata.uiType,
      audience: metadata.audience,
    },
  };
}

export function formatErrorReportAsMarkdown(errorReport: ErrorReport): string {
  const errorTypeLabels: Record<ErrorReport['errorType'], string> = {
    validation: 'Image Validation Error',
    vision_api: 'Vision API Error',
    parsing: 'Response Parsing Error',
    no_analysis: 'Analysis Failed',
    unknown: 'Unknown Error',
  };

  return `# AgentUX Analysis Error Report

## Error Summary

**Error Type**: ${errorTypeLabels[errorReport.errorType]}

**Message**: ${errorReport.userFriendlyMessage}

${errorReport.metadata ? `
## Context

- **Platform**: ${errorReport.metadata.platform}
- **UI Type**: ${errorReport.metadata.uiType}
- **Audience**: ${errorReport.metadata.audience}
` : ''}

---

## Error Details

${errorReport.errorMessage}

---

## Recommendations

${errorReport.recommendations.map((rec, idx) => `${idx + 1}. ${rec}`).join('\n')}

---

## Next Steps

1. **Review Recommendations**: Follow the suggestions above to resolve the issue
2. **Retry Analysis**: After addressing the issue, try running the analysis again
3. **Check Logs**: Review AgentUX output logs for additional technical details
4. **Contact Support**: If the issue persists, consider reporting it with the error details above

---

## Technical Information

**Error Type**: ${errorReport.errorType}
**Raw Error**: ${errorReport.errorMessage}

---

*Error report generated by AgentUX*
`;
}

