import * as path from 'path';
import { promises as fs } from 'fs';
import { exec } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);

/**
 * Comprehensive test analysis script
 * Runs full analysis pipeline on source images and generates detailed reports
 */

interface TestResult {
  imageName: string;
  sourceImagePath: string;
  analysisStatePath: string;
  overlayImagePath: string;
  qualityAnalysisPath: string;
  visualAccuracyPath: string;
  success: boolean;
  errors: string[];
}

async function runComprehensiveAnalysis(
  sourceImagePath: string,
  outputDir: string = 'artifacts/tests',
): Promise<TestResult> {
  const imageName = path.basename(sourceImagePath, path.extname(sourceImagePath));
  const errors: string[] = [];

  console.log(`\n${'='.repeat(80)}`);
  console.log(`Analyzing: ${imageName}`);
  console.log('='.repeat(80));

  try {
    // Step 1: Run analysis (using test script)
    console.log('\n1. Running Vision API analysis...');
    const analysisStatePath = path.join(outputDir, 'state', `${imageName}.json`);
    
    // Note: This assumes analysis has already been run
    // In practice, you'd call the analysis command here
    console.log('   (Assuming analysis already completed)');

    // Step 2: Generate overlay
    console.log('\n2. Generating overlay image...');
    const overlayImagePath = path.join(outputDir, `${imageName}-overlay.png`);
    
    // Check if state exists
    try {
      await fs.access(analysisStatePath);
      
      // Generate overlay using render-overlay script logic
      // For now, we'll assume it's generated separately
      console.log('   Overlay will be generated...');
    } catch {
      errors.push(`Analysis state not found: ${analysisStatePath}`);
    }

    // Step 3: Run quality analysis
    console.log('\n3. Running quality analysis...');
    const qualityAnalysisPath = path.join(outputDir, `QUALITY_ANALYSIS_${imageName}.md`);
    
    try {
      const { stdout } = await execAsync(
        `npx ts-node scripts/analyze-output-quality.ts "${sourceImagePath}" "${analysisStatePath}" "${overlayImagePath}"`,
      );
      console.log('   Quality analysis complete');
    } catch (error) {
      errors.push(`Quality analysis failed: ${error}`);
    }

    // Step 4: Run visual accuracy check
    console.log('\n4. Running visual accuracy check...');
    const visualAccuracyPath = path.join(outputDir, `VISUAL_ACCURACY_${imageName}.md`);
    
    try {
      const { stdout } = await execAsync(
        `npx ts-node scripts/visual-accuracy-check.ts "${sourceImagePath}" "${overlayImagePath}" "${analysisStatePath}"`,
      );
      console.log('   Visual accuracy check complete');
    } catch (error) {
      errors.push(`Visual accuracy check failed: ${error}`);
    }

    const success = errors.length === 0;

    return {
      imageName,
      sourceImagePath,
      analysisStatePath,
      overlayImagePath,
      qualityAnalysisPath,
      visualAccuracyPath,
      success,
      errors,
    };
  } catch (error) {
    errors.push(`Comprehensive analysis failed: ${error}`);
    return {
      imageName,
      sourceImagePath,
      analysisStatePath: '',
      overlayImagePath: '',
      qualityAnalysisPath: '',
      visualAccuracyPath: '',
      success: false,
      errors,
    };
  }
}

async function generateSummaryReport(results: TestResult[]): Promise<string> {
  const total = results.length;
  const successful = results.filter((r) => r.success).length;
  const failed = results.filter((r) => !r.success).length;

  return `# Comprehensive Test Analysis Summary

## Overview

- **Total Images**: ${total}
- **Successful**: ${successful} (${((successful / total) * 100).toFixed(1)}%)
- **Failed**: ${failed} (${((failed / total) * 100).toFixed(1)}%)

---

## Results by Image

${results.map((result) => `
### ${result.imageName}

**Status**: ${result.success ? '✅ SUCCESS' : '❌ FAILED'}

- **Source**: ${result.sourceImagePath}
- **State**: ${result.analysisStatePath}
- **Overlay**: ${result.overlayImagePath}
- **Quality Report**: ${result.qualityAnalysisPath}
- **Visual Accuracy**: ${result.visualAccuracyPath}

${result.errors.length > 0 ? `**Errors**:\n${result.errors.map((e) => `- ${e}`).join('\n')}` : ''}
`).join('\n')}

---

## Overall Assessment

${successful === total ? '✅ All analyses completed successfully' : `⚠️ ${failed} analysis(ies) failed`}

---

*Generated by AgentUX Comprehensive Test Analyzer*
`;
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  if (args.length === 0) {
    console.error('Usage: ts-node comprehensive-test-analysis.ts <image1> [image2] [image3] ...');
    console.error('Or: ts-node comprehensive-test-analysis.ts --dir <directory>');
    process.exit(1);
  }

  const outputDir = path.resolve(process.cwd(), 'artifacts/tests');
  await fs.mkdir(outputDir, { recursive: true });
  await fs.mkdir(path.join(outputDir, 'state'), { recursive: true });

  const imagePaths: string[] = [];
  
  if (args[0] === '--dir') {
    // Load all images from directory
    const dir = args[1] || 'fixtures/images/real';
    const files = await fs.readdir(dir);
    imagePaths.push(...files.filter((f) => f.match(/\.(png|jpg|jpeg)$/i)).map((f) => path.join(dir, f)));
  } else {
    imagePaths.push(...args.map((p) => path.resolve(p)));
  }

  console.log(`\n📸 Found ${imagePaths.length} image(s) to analyze\n`);

  const results: TestResult[] = [];
  for (const imagePath of imagePaths) {
    const result = await runComprehensiveAnalysis(imagePath, outputDir);
    results.push(result);
  }

  // Generate summary
  const summary = await generateSummaryReport(results);
  const summaryPath = path.join(outputDir, 'COMPREHENSIVE_TEST_SUMMARY.md');
  await fs.writeFile(summaryPath, summary);

  console.log(`\n${'='.repeat(80)}`);
  console.log('Comprehensive Analysis Complete');
  console.log('='.repeat(80));
  console.log(`\nSummary saved to: ${summaryPath}`);
  console.log(`\nSuccessful: ${results.filter((r) => r.success).length}/${results.length}`);
}

main();

